### ISSUE TITLE
[Suggestion] Delete data

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#2]
To save on disk space and just.. speed in general, the warning data should get deleted either after x time has passed with 0 warnings for a user, or when the user is pardoned.

**Comment by NexInfinite** [comment]
Sure! Let me update that now :D

**Comment by NexInfinite** [comment]
https://github.com/NexInfinite/DiscordBotHelp/commit/8011ea3eb0e77a53df40f50bd9b2f21d4dceb301 Update pushed, it works off the the user typing in chat; this is a very very simple way of doing it, can be made more efficient by removing the if statement for on_message in warn.py. Is there anything else you would like?

**Comment by NexInfinite** [comment]
https://github.com/NexInfinite/DiscordBotHelp/commit/48877cc6520ba458040f2887676d919b064c908b ok I had to fix the if statement, it was bugging me haha :D

**Comment by NexInfinite** [comment]
Going to close this, if you have anything else you want just open a new ticket 😄

**Comment by Motzumoto** [comment]
re-opening this because of an attribute error 
`AttributeError: module 'datetime' has no attribute 'now'`
Im importing datetime, what did you import for this to work? 


After doing `from datetime import datetime` i get this new error

`
  File "C:\Users\cuzto\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\cuzto\Desktop\agb local\Cogs\mod.py", line 696, in on_message
    end = datetime.strptime(user["warn_time"], "%m/%d/%Y")
KeyError: 'warn_time'`

**Comment by NexInfinite** [comment]
https://github.com/NexInfinite/DiscordBotHelp/issues/5 check this
