### ISSUE TITLE
[Another Suggestion] Add reasons to warnings

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#3]
I was going to add this myself but json files are really finicky and personally im still learning how to use them. I'd be nice if there was reasons to warnings so people could see what the user did, 

[p]infractions @user 
User has x warnings for: {reason}

The reason would be stored in the warns.json file im pretty sure

**Comment by NexInfinite** [comment]
Another great idea, I will also work on this when I have some free time :D

**Comment by Motzumoto** [comment]
to add onto this: When you do the infractions command it should show this
Warning((if warning== > 1: Warnings): x
Reason: x reason
Warned by: User

I can add more detail to the warning to make it have proper grammar if you want
