### ISSUE TITLE
[Issue] Sending Webhook messages

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#4]
If you use the webhook sender with an @ everyone, it will work. Something like `allowed_mentions=discord.AllowedMentions(everyone=False, roles=False, users=False)` would prevent this, but i don't even know how webhooks work atm, I'm trying to implement it myself but its not working.

**Comment by NexInfinite** [comment]
One way of doing it is to simply check if the user did <@everyone> <@&roleid> or <@!userid> and if they did; simply either come back with an error message or strip it from the message. I can work on this soon :D
