### ISSUE TITLE
[help command]

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#7]
Wouldnt it be better to subclass the help command? i found a pretty useful gist post about it, [you can find it here](https://gist.github.com/InterStella0/b78488fb28cadf279dfd3164b9f0cf96#embed-minimalhelpcommand)

**Comment by NexInfinite** [comment]
I mean it could be better to do it this way and I may look into it in the future but this help command is still very much functional. I'll see what I can do if I get time

**Comment by Motzumoto** [comment]
People like subclassing for some reason, and its also easier to subclass since you dont need to remove the help command manually

**Comment by NexInfinite** [comment]
Yeah I see, I'll look into it
