### ISSUE TITLE
[Command Idea] Blacklist

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#8]
Ive wondered for a while how i could make a blacklist command but im not sure how that could work for all commands. I know you can just add a list of userID's to return to, but that seems a bit... unconventional.

**Comment by NexInfinite** [comment]
Make a class so that you can add a decorator that will check if the user is in the list of commands. For example
```python
from blacklist import blacklist

@blacklist("list1")
@commands.command(name="command")
async def command_with_blacklist(self, ctx):
    """do somin"""
    # Code here
```
I can probably whip up an example soon but I'm still working on the help command upgrades

**Comment by Motzumoto** [comment]
accidently closed this, my bad. But yeah, if you could put an example or something that would be really nice

**Comment by NexInfinite** [comment]
Yeah, I can do that once help command is done. Got some things irl to do then, if I have time, I'll start work on it. Me big big busy

**Comment by Motzumoto** [comment]
> Yeah, I can do that once help command is done. Got some things irl to do then, if I have time, I'll start work on it. Me big big busy

Alright, take your time. Im actually really appreciative of this repo. thanks for everything you've posted.

**Comment by NexInfinite** [comment]
> > Yeah, I can do that once help command is done. Got some things irl to do then, if I have time, I'll start work on it. Me big big busy
> 
> Alright, take your time. Im actually really appreciative of this repo. thanks for everything you've posted.

No bother, I am happy you enjoy everything :D
